sudo: required
language: java
jdk: oraclejdk8
services:
  - docker
script:
  - gradle wrapper
  - ./gradlew clean
  - ./gradlew build buildDocker --info

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sh ./deploy/docker_pusher.sh