server:
  port: 8806


spring:
  application:
    name: device-center
  datasource:
    url: jdbc:postgresql://localhost:5432/device_center
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: com.umasuo.database.dialect.JSONBPostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update

jwt:
  secret: QWERTYUIOPASDFGHJKLZXCVBNM
  expires: 72000

message:
  broker:
    host: localhost
    port: 1883
    username: username
    password: password

product:
  service:
    url: http://localhost:8805/